//
// Generated file, do not edit! Created by opp_msgc 4.1 from data/Package.msg.
//

#ifndef _PACKAGE_M_H_
#define _PACKAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0401
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>data/Package.msg</tt> by opp_msgc.
 * <pre>
 * packet Package {
 *     int destination;
 *     int source;
 *     int sessionId;
 *     int packetId;
 *     int priority;
 *     int size;
 * }
 * </pre>
 */
class Package : public ::cPacket
{
  protected:
    int destination_var;
    int source_var;
    int sessionId_var;
    int packetId_var;
    int priority_var;
    int size_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Package&);

  public:
    Package(const char *name=NULL, int kind=0);
    Package(const Package& other);
    virtual ~Package();
    Package& operator=(const Package& other);
    virtual Package *dup() const {return new Package(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getDestination() const;
    virtual void setDestination(int destination_var);
    virtual int getSource() const;
    virtual void setSource(int source_var);
    virtual int getSessionId() const;
    virtual void setSessionId(int sessionId_var);
    virtual int getPacketId() const;
    virtual void setPacketId(int packetId_var);
    virtual int getPriority() const;
    virtual void setPriority(int priority_var);
    virtual int getSize() const;
    virtual void setSize(int size_var);
};

inline void doPacking(cCommBuffer *b, Package& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Package& obj) {obj.parsimUnpack(b);}


#endif // _PACKAGE_M_H_
